[package]
name = "LLVM-Compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
strum = { version = "0.24.1", features = ["phf"] }
strum_macros = "0.24.3"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.17.0"
hashbrown = "0.13.2"

[profile.release]
lto = true
